apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80   # Port: Some times your application inside container serves different services on a different port. 
      targetPort: 8000    # TargetPort: This is the actual port on which your application is running inside the container. 
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007


#    nodePort: The port on the node where external traffic will come in on.
#    port: The port of this service.
#    targetPort: The target port on the pod(s) to forward traffic to.
